CREATE TABLE "Contract" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" INT REFERENCES "User" ("id"),
  "userRoleID" INT REFERENCES "UserRole" ("id"),
  "contractTypeID" INT REFERENCES "ContractType" ("id"),
  "salaryPackageID" INT REFERENCES "SalaryPackageType" ("id"),
  "jobRoleID" INT REFERENCES "JobRole" ("id"),
  "startDate" TIMESTAMP WITH TIME ZONE,
  "expiryDate" TIMESTAMP WITH TIME ZONE
);
