CREATE TABLE "TrainingSession" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "trainingID" INT REFERENCES "Training" ("id"),
  "trainerID" INT REFERENCES "User" ("id"),
  "startDateTime" TIMESTAMP WITH TIME ZONE,
  "endDateTime" TIMESTAMP WITH TIME ZONE
);