CREATE TABLE "TrainingSubscription" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userID" INT REFERENCES "User" ("id"),
  "trainingSessionID" INT REFERENCES "TrainingSession" ("id"),
  "subscriptionDate" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
