CREATE TABLE "User" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR,
  "surname" VARCHAR,
  "email" VARCHAR,
  "username" VARCHAR,
  "password" BYTEA,
  "salt" BYTEA,
  "address" VARCHAR,
  "userRoleID" INT REFERENCES "UserRole" ("id"),
  "profileImage" BYTEA
);
