CREATE TABLE "User" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "surname" varchar,
  "email" varchar,
  "username" varchar,
  "password" bytea,
  "salt" bytea,
  "addres" varchar,
  "userRoleID" int,
  "profileImage" bytea
);

ALTER TABLE "User" ADD FOREIGN KEY ("userRoleID") REFERENCES "UserRole" ("id");

ALTER TABLE "User" ALTER COLUMN password TYPE bytea USING password::TEXT::BYTEA;

ALTER TABLE "User" ADD COLUMN salt bytea;

ALTER TABLE "User" ADD COLUMN profileImage bytea;